- lang: EN
  param:
  - targets:
    - cat1
    - cat2
  - skip_cats:
    - cat3
    - cat4
  - outfile: data/en_articles.json
- lang: ES
  param:
  - targets:
    - cat1
    - cat2
  - skip_cats:
    - cat3
    - cat4
  - outfile: data/es_articles.json
- lang: ZH
  param:
  - targets:
    - cat1
    - cat2
  - skip_cats:
    - cat3
    - cat4
  - outfile: data/zh_articles.json
