- lang: EN
  param:
    targets:
    - Category:Intersex
    skip_cats:
    - Category:Same-sex sexuality
    - Category:LGBT and society
    - Category:Homosexuality
    
    outfile: data/test_pages_out.json
