- lang: EN
  param:
  - targets:
    - Category:Intersex
    - Category:LGBT culture
  - skip_cats:
    - Category:Same-sex sexuality
    - Category:LGBT and society
    - Category:Homosexuality
    
  - outfile: data/test_pages_out.json
